version: "3.9"

services:
  app_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_backend
    restart: always
    env_file: ./config/.env
    volumes:
      - static:/app/static
      - media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - app_db

  app_db:
    image: postgres:14.4
    container_name: postgres_db
    env_file: ./config/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always


volumes:
  postgres_data:
  static:
  media: