# Generated by Django 4.1.3 on 2022-11-13 11:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AccountTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_name', models.CharField(default='Basic', max_length=75)),
                ('thumbnail_sizes', models.CharField(default=None, max_length=150, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('original_link', models.BooleanField(default=False)),
                ('expiring_links', models.BooleanField(default=False)),
                ('min_expiring_time', models.PositiveIntegerField(default=0)),
                ('max_expiring_time', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, default=None, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(blank=True, default=None, height_field='image_height', upload_to='images/', width_field='image_width')),
                ('image_height', models.PositiveIntegerField(default=0)),
                ('image_width', models.PositiveIntegerField(default=0)),
                ('caption', models.CharField(blank=True, default=None, max_length=75)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
                ('thumbnails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.thumbnail')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='account_tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.accounttier'),
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
