# Generated by Django 3.2 on 2022-11-18 20:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AccountTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_name', models.CharField(default='Basic', max_length=75)),
                ('thumbnail_sizes', models.CharField(default=None, max_length=150, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('original_link', models.BooleanField(default=False)),
                ('expiring_links', models.BooleanField(default=False)),
                ('min_expiring_time', models.PositiveIntegerField(default=0)),
                ('max_expiring_time', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('image_file', versatileimagefield.fields.VersatileImageField(height_field='height', upload_to='images/', verbose_name='Image', width_field='width')),
                ('caption', models.CharField(blank=True, default=None, max_length=75)),
                ('image_ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
            ],
        ),
        migrations.CreateModel(
            name='ExpiringLinkToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateTimeField()),
                ('expires_in', models.IntegerField(default=0)),
                ('image', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.image')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='account_tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.accounttier'),
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
