# Generated by Django 4.1.3 on 2022-11-13 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='thumbnails',
        ),
        migrations.RemoveField(
            model_name='thumbnail',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='thumbnail',
            name='image',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.image'),
        ),
    ]
