# Generated by Django 3.2 on 2022-11-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20221114_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='height_field',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='width_field',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
