# Generated by Django 3.2 on 2022-11-15 08:38

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20221114_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='height_field',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='width_field',
            new_name='width',
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=versatileimagefield.fields.VersatileImageField(height_field=models.PositiveIntegerField(default=0), upload_to='images/', verbose_name='Image', width_field=models.PositiveIntegerField(default=0)),
        ),
    ]
