# Generated by Django 3.2 on 2022-11-15 09:03

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20221115_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_tier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.accounttier'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=versatileimagefield.fields.VersatileImageField(height_field='height', upload_to='images/', verbose_name='Image', width_field='width'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='image',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.image'),
        ),
    ]
