# Generated by Django 3.2 on 2022-11-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20221115_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='template',
            field=models.CharField(blank=True, default=None, max_length=1500),
        ),
    ]
