# Generated by Django 3.2 on 2022-11-18 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_image_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.accounttier'),
        ),
    ]
