# Generated by Django 4.1.3 on 2022-11-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(blank=True, default=None, height_field='image_height', upload_to='images/')),
                ('image_height', models.PositiveIntegerField(default=0)),
                ('thumbnail', models.ImageField(blank=True, default=None, upload_to='images/')),
                ('caption', models.CharField(blank=True, default=None, max_length=75)),
            ],
        ),
    ]
