# Generated by Django 4.1.3 on 2022-11-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_account_image_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='expiring_links',
        ),
        migrations.RemoveField(
            model_name='account',
            name='original_image',
        ),
        migrations.RemoveField(
            model_name='account',
            name='thumbnails_size_list',
        ),
        migrations.AddField(
            model_name='account',
            name='account_tier',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Premium', 'Premium'), ('Enterprise', 'Enterprise')], default='Basic', max_length=100),
        ),
    ]
